load("@rules_cc//cc:cc_library.bzl", "cc_library")

genrule(
    name = "config_h",
    srcs = ["config.h.bazel"],
    outs = ["config.h"],
    cmd_bash = """
        root=$$(pwd)
        sed -e "s|@CECEILIA_ROOT@|$$root|g" \
            $< > $@
    """,
    cmd_ps = """
        $$root = $$PWD.Path.Replace('\\', '/')
        $$content = Get-Content -Raw '$<'
        $$content = $$content -replace '@CECEILIA_ROOT@', $$root
        Set-Content -Path '$@' -Value $$content -NoNewline
    """,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "config",
    hdrs = [":config_h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "include",
    hdrs = [
        "include/Ahri/Ahri.cuh",
        "include/Ahri/Ahri.h",
        "include/Ahri/Ahri.hpp",
        "include/Ahri/Ahri.ixx",
        "include/Ahri/Ceceilia.cuh",
        "include/Ahri/Ceceilia.h",
        "include/Ahri/Ceceilia.hpp",
        "include/Ahri/Nono.cuh",
        "include/Ahri/Nono.h",
        "include/Ahri/Nono.hpp",
        "include/Ahri/Nono.ixx",
        "include/Ahri/Sokyoei.cuh",
        "include/Ahri/Sokyoei.h",
        "include/Ahri/Sokyoei.hpp",
        "include/Ahri/Sokyoei.ixx",
        "include/Ahri/Utils.h",
        "include/Ahri/Utils.hpp",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
