target("cfile")
    set_kind("binary")
    add_files("cfile.c")
target_end()

target("file")
    set_kind("binary")
    add_files("file.cpp")
target_end()

-- add_executable(json_file json_file.cpp)
-- target_link_libraries(json_file PRIVATE nlohmann_json::nlohmann_json)
target("json_file")
    set_kind("binary")
    add_files("json_file.cpp")
    add_packages("nlohmann_json")
target_end()

-- add_executable(toml_file toml_file.cpp)
-- target_link_libraries(toml_file PRIVATE toml11::toml11)
target("toml_file")
    set_kind("binary")
    add_files("toml_file.cpp")
    -- add_packages("toml11")
    add_packages("toml++")
target_end()

-- add_executable(xml_file xml_file.cpp)
-- target_link_libraries(xml_file PRIVATE tinyxml2::tinyxml2)
target("xml_file")
    set_kind("binary")
    add_files("xml_file.cpp")
    add_packages("tinyxml2")
target_end()

-- add_executable(yaml_file yaml_file.cpp)
-- target_link_libraries(yaml_file PRIVATE yaml-cpp::yaml-cpp)
target("yaml_file")
    set_kind("binary")
    add_files("yaml_file.cpp")
    add_packages("yaml-cpp")
target_end()
