target("cfile")
    set_kind("binary")
    add_files("cfile.c")
target_end()

target("file")
    set_kind("binary")
    add_files("file.cpp")
target_end()

target("json_file")
    set_kind("binary")
    add_files("json_file.cpp")
    add_packages("nlohmann_json")
target_end()

target("toml_file")
    set_kind("binary")
    add_files("toml_file.cpp")
    -- add_packages("toml11")
    add_packages("toml++")
target_end()

target("xml_file")
    set_kind("binary")
    add_files("xml_file.cpp")
    add_packages("tinyxml2")
target_end()

target("yaml_file")
    set_kind("binary")
    add_files("yaml_file.cpp")
    add_packages("yaml-cpp")
target_end()
